# Generated by Django 3.1.3 on 2020-12-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('rating', models.PositiveIntegerField(null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('stock', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
